stages:
    get_data:
      cmd: python src/stage01_load_and_save_data.py --config=configs/config.yaml
      deps:
        - src/stage01_load_and_save_data.py
        - src/utils/common_utils.py
        - configs/config.yaml
      outs:
        - data/data.csv

    split_data:
      cmd: python src/stage02_split_data.py --config=configs/config.yaml
      deps:
        - src/stage02_split_data.py
        - src/utils/common_utils.py
        - configs/config.yaml
        - data/data.csv
      outs:
        - artifacts/processed_data/train.csv
        - artifacts/processed_data/test.csv

    train_model:
      cmd: python src/stage03_train.py --config=configs/config.yaml --params=params.yaml
      deps:
        - src/stage03_train.py
        - src/utils/common_utils.py
        - configs/config.yaml
        - params.yaml
        - artifacts/processed_data/train.csv
      outs:
        - artifacts/saved_models/model.joblib
        - artifacts/reports/params.json