base:
    project: 'simple-LinearRegression-dvc'
    test_size: 0.2
    random_state: 42
    target_col: Actual_MPG

remote_data_source:
    path: 'C:/Users/acreddy/Desktop/ML/cars_mpg.csv'    

local_data_source: 
    data_dir: data
    data_file: data/data.csv
    
artifacts:
    artifacts_dir: artifacts

    split_data:
        processed_data_dir: artifacts/processed_data
        train_data_path: artifacts/processed_data/train.csv
        test_data_path: artifacts/processed_data/test.csv
      
    reports:
        reports_dir: artifacts/reports
        parameters: artifacts/reports/params.json
        scores: artifacts/reports/scores.json

    model_dir: artifacts/saved_models
    model_path: artifacts/saved_models/model.joblib
